# Generated by Django 5.0.4 on 2024-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_react_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Pesho', max_length=50),
            preserve_default=False,
        ),
    ]
